knpu_oauth2_client:
  clients:
    google:
      type: google
      client_id: '%env(OAUTH_GOOGLE_ID)%'
      client_secret: '%env(OAUTH_GOOGLE_SECRET)%'
      redirect_route: auth_oauth_check
      redirect_params:
        service: google
